### ISSUE TITLE
Firefox issue

### ISSUE THREAD

**Issue by macsupport** [nicinabox/superslides#160]
In Firefox, at least on a Mac, the text for ".slides-pagination a" in the nav, shows in the links. I can see the numbers for each link in your online demo.

**Comment by yogoo** [comment]
I'm seeing this as well with 0.6.2 in Firefox 25.0.1 under OS X 10.9. The latest Chrome and Safari are exempt from this.

A workaround is to set a text-indent high enough to hide the text such as :

``` css
.slides-pagination a { text-indent: -150%; }
```
