### ISSUE TITLE
issue with safari flicker fix

### ISSUE THREAD

**Issue by mpolom** [nicinabox/superslides#33]
v0.4.3 fixes the safari flicker issue, but now I have the issue that any sliders that are loaded are hidden until highlighted. I don't know if this is an issue specifically with my code as I am using slider elements with 0.6 opacity.

Removed the following line and it seems to work fine...

``` css
#slides .slides-container img {
  -webkit-backface-visibility: hidden;
}
```
